name: CMake Windows 2022

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Create Build Dir, build and push
        run: |
          mkdir build
          cd build
          ls
          cmake -G "Visual Studio 17 2022" ../llvm
          cmake --build . --config ${{env.BUILD_TYPE}}
          git config --global user.email "dummy@dummyEmails.com"
          git config --global user.name "Dummy Dummy"
          git commit -m "Upload Build ${{env.BUILD_TYPE}}"
          git push -u origin build
