name: CMake Windows 2022

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Create and CD to Build Dir
        run: |
          mkdir build
          cd build

      - name: Create Build Cache
        run: cmake -G "Visual Studio 17 2022" ../llvm

      - name: Build
        # Build your program with the given configuration
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install

      - name: Switch Branch
        run: git branch build

      - name: Commit to GitHub
        run: git --commit -m "Upload Build"

      - name: Push to Github
        run: git push -u origin build

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}}
