name: CMake

on: workflow_dispatch
#   push:
#     branches: [ "release/15.x" ]
#   pull_request:
#     branches: [ "release/15.x" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Ninja Tool
      run: |
          sudo apt-get update
          sudo apt-get -y install ninja-build
    
    - name: Create Build Dir
      run: mkdir build
      
    - name: CD Build
      run: cd build
      
    - name: Create Build Cache
      run: cmake -G "Ninja" ../llvm-project-fork

    - name: Build
      # Build your program with the given configuration
      run: cmake --build . --config ${{env.BUILD_TYPE}} --target install
      
    - name: Switch Branch
      run: git branch build
      
    - name: Commit to GitHub
      run: git --commit -m "Upload Build"
      
    - name: Push to Github
      run: git push -u origin build

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
